export {
  applyAction,
  applyV2Action,
  buildV2PlayerView,
  buildV2SpectatorView,
  createInitialState,
  createV2InitialState,
  getOutcome,
  getPlayerView,
  getSpectatorView,
  getV2Outcome,
  validateV2Action,
} from './game.js';
export {
  TRAGEDY_GAME_ID,
  TRAGEDY_SYSTEM_ACTION_TYPES,
  TragedyOfTheCommonsPlugin,
  TragedyOfTheCommonsV2Plugin,
} from './plugin.js';
export type {
  EcosystemKind,
  ExtractionLevel,
  ResourceInventory,
  ResourceType,
  TragedyAction,
  TragedyBoardTile,
  TragedyConfig,
  TragedyEcosystem,
  TragedyOutcome,
  TragedyPhase,
  TragedyPlayerRanking,
  TragedyPlayerState,
  TragedyRegion,
  TragedyState,
  TragedyTerrain,
  TragedyTradeOffer,
  TragedyV2Action,
  TragedyV2Config,
  TragedyV2Outcome,
  TragedyV2SpectatorView,
  TragedyV2State,
} from './types.js';
export { DEFAULT_TRAGEDY_CONFIG, DEFAULT_V2_CONFIG, EMPTY_INVENTORY } from './types.js';
