#!/usr/bin/env -S npx tsx
/**
 * Generate `wiki/reference/cli.md` from the live Commander tree in
 * `packages/cli/src/index.ts`.
 *
 * Run via `npm run gen:cli-ref` (also wired as a `prebuild` hook).
 *
 * The output is deterministic: same source tree → same bytes. Commands are
 * sorted alphabetically within each domain group; groups are emitted in a
 * fixed order. No timestamps, no environment-derived values beyond the CLI
 * `version` (read from `packages/cli/package.json`).
 *
 * The "trust" group lists planned-but-unimplemented stubs. Those commands
 * are not registered in the shipping CLI (see `packages/cli/src/index.ts`),
 * so this script imports `registerTrustCommands` directly and attaches them
 * to a side copy of the program purely for documentation purposes. The
 * shipping CLI is unaffected.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Command, Argument as CommanderArgument, Option as CommanderOption } from 'commander';
import { registerTrustCommands } from '../packages/cli/src/commands/trust.js';
import { program } from '../packages/cli/src/index.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..');
const OUTPUT_PATH = path.join(REPO_ROOT, 'wiki', 'reference', 'cli.md');
const CLI_PACKAGE_JSON = path.join(REPO_ROOT, 'packages', 'cli', 'package.json');

// ---------------------------------------------------------------------------
// Group plan
// ---------------------------------------------------------------------------

interface GroupSpec {
  id: string;
  title: string;
  intro: string;
  commands: string[];
  /** Optional callout markdown rendered before the command list. */
  callout?: string;
}

// Confirm which trust-spec doc actually exists at write time.
function trustSpecLink(): string {
  const planPath = path.join(REPO_ROOT, 'docs', 'plans', 'trust-plugins.md');
  const oldSpec = path.join(REPO_ROOT, 'docs', 'TRUST_PLUGINS_SPEC.md');
  try {
    readFileSync(planPath);
    return 'docs/plans/trust-plugins.md';
  } catch {
    /* fall through */
  }
  try {
    readFileSync(oldSpec);
    return 'docs/TRUST_PLUGINS_SPEC.md';
  } catch {
    return 'docs/plans/trust-plugins.md';
  }
}

const GROUPS: GroupSpec[] = [
  {
    id: 'identity',
    title: 'Identity',
    intro:
      'Bootstrap your local identity, register a human-readable name on-chain, and inspect status. Run `init` once to generate a key, then `check-name` and `register` to claim a handle.',
    commands: ['init', 'status', 'check-name', 'register'],
  },
  {
    id: 'wallet',
    title: 'Wallet',
    intro:
      'Inspect balances, fund your account, withdraw credits back to USDC, and import or export your key file. Withdrawal is two-step (request, then execute after the burn cooldown).',
    commands: ['balance', 'fund', 'withdraw', 'export-key', 'import-key'],
  },
  {
    id: 'lobbies-games',
    title: 'Lobbies & Games',
    intro:
      'Discover, create, and join lobbies, then drive gameplay through the unified phase-tool dispatch. `state` and `wait` are the agent loop primitives; `tools` and `tool` are how plugins and game phases expose actions.',
    commands: ['lobbies', 'create-lobby', 'join', 'guide', 'state', 'wait', 'tools', 'tool'],
  },
  {
    id: 'verification',
    title: 'Verification',
    intro:
      'Independently verify a finished game against on-chain records: config hash, EIP-712 move signatures, and Merkle root of all turns.',
    commands: ['verify'],
  },
  {
    id: 'trust',
    title: 'Trust (planned)',
    intro:
      'Trust attestations and reputation queries. These commands are not yet shipped in the running CLI — they are placeholders for the trust-graph plugin.',
    callout: `> **Planned, not implemented.** These commands are stubs that exit with \`Not yet implemented\`. Tracked under the trust-graph plugin work — see [\`${trustSpecLink()}\`](../../${trustSpecLink()}).`,
    commands: ['attest', 'revoke', 'reputation'],
  },
  {
    id: 'mcp',
    title: 'MCP server',
    intro:
      'Run the CLI as an MCP server so AI tools (Claude Code, Claude Desktop, OpenAI HTTP MCP clients) can drive gameplay via the same tool surface as the shell CLI.',
    commands: ['serve'],
  },
];

// ---------------------------------------------------------------------------
// Markdown rendering
// ---------------------------------------------------------------------------

const HEADER_WARNING =
  '<!-- AUTO-GENERATED by scripts/gen-cli-reference.ts. Do not edit by hand. Run `npm run gen:cli-ref` to regenerate. -->';

function escapePipes(text: string): string {
  return text.replace(/\|/g, '\\|');
}

function escapeCell(text: string): string {
  // Keep table cells single-line and pipe-safe.
  return escapePipes(text.replace(/\r?\n/g, ' ').trim());
}

function commandSynopsis(cmd: Command): string {
  // `coga <name> [options] <required> [optional...]`
  const argParts: string[] = [];
  for (const arg of getArguments(cmd)) {
    const tail = arg.variadic ? '...' : '';
    argParts.push(arg.required ? `<${arg.name()}${tail}>` : `[${arg.name()}${tail}]`);
  }
  const visibleOptions = getVisibleOptions(cmd);
  const optionPart = visibleOptions.length > 0 ? '[options]' : '';
  return ['coga', cmd.name(), optionPart, ...argParts].filter(Boolean).join(' ');
}

function getArguments(cmd: Command): CommanderArgument[] {
  // Commander v14: registeredArguments is the public API for declared args.
  const args = (cmd as Command & { registeredArguments?: CommanderArgument[] }).registeredArguments;
  return Array.isArray(args) ? args : [];
}

function getVisibleOptions(cmd: Command): CommanderOption[] {
  // Filter options the source intentionally hid by passing `undefined` as
  // description (Commander stores those as empty strings). These are
  // internal/testing flags that should not appear in user-facing docs.
  return cmd.options.filter((opt) => {
    if (opt.hidden) return false;
    if (!opt.description || opt.description.trim() === '') return false;
    return true;
  });
}

function argTypeLabel(arg: CommanderArgument): string {
  if (arg.variadic) return 'string[]';
  return 'string';
}

function defaultValueLabel(value: unknown): string {
  if (value === undefined) return '';
  if (typeof value === 'string') return `\`${value}\``;
  return `\`${JSON.stringify(value)}\``;
}

function renderArgumentsTable(cmd: Command): string {
  const args = getArguments(cmd);
  if (args.length === 0) return '';
  const lines: string[] = [
    '**Arguments**',
    '',
    '| Name | Type | Required | Description |',
    '| --- | --- | --- | --- |',
  ];
  for (const arg of args) {
    const desc = arg.description ?? '';
    const required = arg.required ? 'yes' : 'no';
    lines.push(
      `| \`${escapeCell(arg.name())}\` | ${argTypeLabel(arg)} | ${required} | ${escapeCell(desc) || '—'} |`,
    );
  }
  return lines.join('\n');
}

function renderOptionsTable(cmd: Command): string {
  const options = getVisibleOptions(cmd);
  if (options.length === 0) return '';
  const lines: string[] = [
    '**Options**',
    '',
    '| Flag | Default | Description |',
    '| --- | --- | --- |',
  ];
  // Sort options alphabetically by long flag for determinism.
  const sorted = [...options].sort((a, b) => {
    const al = (a.long ?? a.flags).toLowerCase();
    const bl = (b.long ?? b.flags).toLowerCase();
    if (al < bl) return -1;
    if (al > bl) return 1;
    return 0;
  });
  for (const opt of sorted) {
    const def = defaultValueLabel(opt.defaultValue);
    lines.push(
      `| \`${escapeCell(opt.flags)}\` | ${def || '—'} | ${escapeCell(opt.description ?? '') || '—'} |`,
    );
  }
  return lines.join('\n');
}

function renderCommand(cmd: Command): string {
  const parts: string[] = [];
  parts.push(`### \`${commandSynopsis(cmd)}\``);
  parts.push('');
  const desc = cmd.description() ?? '';
  if (desc) {
    parts.push(desc);
    parts.push('');
  }
  const argTable = renderArgumentsTable(cmd);
  if (argTable) {
    parts.push(argTable);
    parts.push('');
  }
  const optTable = renderOptionsTable(cmd);
  if (optTable) {
    parts.push(optTable);
    parts.push('');
  }
  return parts.join('\n').replace(/\n+$/, '\n');
}

function renderGroup(group: GroupSpec, byName: Map<string, Command>): string {
  const parts: string[] = [];
  parts.push(`## ${group.title}`);
  parts.push('');
  parts.push(group.intro);
  parts.push('');
  if (group.callout) {
    parts.push(group.callout);
    parts.push('');
  }
  // Sort commands alphabetically within the group for determinism.
  const sortedNames = [...group.commands].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
  for (const name of sortedNames) {
    const cmd = byName.get(name);
    if (!cmd) {
      throw new Error(
        `gen-cli-reference: command "${name}" listed in group "${group.id}" was not found in program.commands. Available: ${[...byName.keys()].sort().join(', ')}`,
      );
    }
    parts.push(renderCommand(cmd));
  }
  return parts.join('\n').replace(/\n+$/, '\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function readCliVersion(): string {
  const raw = readFileSync(CLI_PACKAGE_JSON, 'utf8');
  const parsed = JSON.parse(raw) as { version?: unknown };
  if (typeof parsed.version !== 'string' || !parsed.version) {
    throw new Error(`gen-cli-reference: missing "version" in ${CLI_PACKAGE_JSON}`);
  }
  return parsed.version;
}

function main(): void {
  // Attach the planned-but-unshipped trust commands purely for docs. This
  // does not affect the production CLI binary.
  registerTrustCommands(program);

  const byName = new Map<string, Command>();
  for (const cmd of program.commands) {
    byName.set(cmd.name(), cmd);
  }

  // Sanity check: every registered command must be claimed by exactly one
  // group, and every group entry must exist. Fail loudly if a new command
  // ships without being documented.
  const claimed = new Set<string>();
  for (const group of GROUPS) {
    for (const name of group.commands) {
      if (claimed.has(name)) {
        throw new Error(`gen-cli-reference: command "${name}" claimed by multiple groups`);
      }
      claimed.add(name);
    }
  }
  const unclaimed: string[] = [];
  for (const name of byName.keys()) {
    if (!claimed.has(name)) unclaimed.push(name);
  }
  if (unclaimed.length > 0) {
    throw new Error(
      `gen-cli-reference: commands not assigned to any group: ${unclaimed.sort().join(', ')}. Update GROUPS in scripts/gen-cli-reference.ts.`,
    );
  }

  const version = readCliVersion();

  const sections: string[] = [];
  sections.push(HEADER_WARNING);
  sections.push('');
  sections.push('# CLI Reference');
  sections.push('');
  sections.push(
    `Auto-generated reference for the \`coga\` CLI (version \`${version}\`). The CLI is the primary agent surface; the MCP server is a thin wrapper over the same command functions.`,
  );
  sections.push('');
  sections.push(
    'Run `coga --help` for a flat list, `coga <command> --help` for per-command help, or `coga help <command>` for the same.',
  );
  sections.push('');

  for (const group of GROUPS) {
    sections.push(renderGroup(group, byName));
  }

  let output = sections.join('\n').replace(/\n{3,}/g, '\n\n');
  // Guarantee a trailing newline and exactly one blank line between sections.
  if (!output.endsWith('\n')) output += '\n';

  mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, output, 'utf8');
  process.stdout.write(`gen-cli-reference: wrote ${OUTPUT_PATH}\n`);
}

main();
